# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c7223e66ad4b0dfb12918f39d490456c50890aa6e97e6ce12815b7a6c84378be6c774fee2067f6c8dfd91bf01494ef7d909108a46817ca88a5c4657f1a98193

test:
  secret_key_base: c13de86aad2d98a94978317cb66054d32a2432c46a1243f3186448003784b42223575624b8142a826ee65a4a0a7a7bfbf98891b44da38000ab275c0fc4b15117

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
